version: "3.9"

services:
  db:
    image: postgres:16.10-alpine
    container_name: todo_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: todo_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WEB_CONCURRENCY: 1
      LOG_LEVEL: info
    command: ["sh","-c","uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --reload"]
    volumes:
      - ./app:/app/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  postgres_data: {}